name: Build IPF with Java 25

on: [push, pull_request, workflow_dispatch]

env:
  MAVEN_OPTS: -Xmx2048m

# on download timeouts, consider to disable connection pooling
# -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3
# or consider to restrict the ttl
#  -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 25 build
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean test --file pom.xml
